# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Connor Slamowitz
tagline:          '21st Century Explorer'
description:      'Graduate Researcher of Materials at the University of North Carolina - Chapel Hill'
url:              connorslamowitz.github.io/Connor-Slamowitz/
baseurl:          /

author:
  name:           'Connor Slamowitz'

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
