# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Connor
tagline:          'A Scientist'
description:      'Slamowitz'
url:              connorslamowitz.github.io/Connor-Slamowitz/
baseurl:          /

author:
  name:           'Connor Slamowitz'

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
